# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-25 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='pictures')),
                ('slug', models.SlugField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
