# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-25 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_auto_20170629_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='artwork_path',
        ),
        migrations.AddField(
            model_name='musicfile',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
