# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-25 20:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_auto_20170725_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicfile',
            name='slug',
        ),
    ]
