# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-19 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0006_album_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='image_path',
            field=models.ImageField(default='default_image', upload_to=''),
        ),
    ]
