# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-19 17:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0007_album_image_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='image_path',
        ),
    ]
