# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-20 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0008_remove_album_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover',
            field=models.CharField(default='default_image', max_length=30),
        ),
    ]
