# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-24 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0009_album_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongToEdit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=60)),
            ],
        ),
    ]
